# -*- coding: utf-8 -*-
"""Pandas e Polars

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cuE8A26CBEQCwo2RzJ4dVVn8--VJLZsA
"""

#!pip install polars 
#!pip install pyspark
import pandas as pd
import polars as pl
import numpy as np 
import pyspark as ps

"""Arrays base com ternario python """
array = [[f"2023{x*x-(-1)}" for x in range(10)],[x+2**4 for x in range(10)]]

array2 = [["2023"*x for x in range(10)],[x+3**x for x in range(10)]]

array

array2

#Numpy array criado
e = np.random.normal(size=100)

#Numpy para Dataframe em pandas e polars
dfe = pd.DataFrame({"NumpyPD":e})
dfe1=pl.DataFrame({"NumpyPL":e})

#Alrrays para dataframe em pandas e polar
dfe2=pd.DataFrame({"Array1PD":array,"Array2PD":array2})     
dfe3=pl.DataFrame({"Array1PL":array,"Array2PL":array2})

print(dfe) #numpy + pandas

print(dfe1) #numpy + polars

print(dfe2) #Arrays pandas

print(dfe3) #arrays polars



"""Pandas

"""

print(dfe1) #Array 1 PD

df1= pd.DataFrame(array2) #Array 2 PD
print(df1)

"""**Polars quebra quando usa range(1,10)**"""

df2= pl.DataFrame(array) #Array 1 PL 
print(df2)

df2= pl.DataFrame(array2) # Array 2 PL
print(df2)

"""Pyspark 

"""

